# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mlFaceDetector' do
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
        'Core',
        'CxxBridge',
        'DevSupport',
        'RCTText',
        'RCTNetwork',
        'RCTWebSocket',
        'RCTAnimation',
    ]
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'Firebase/Core'
    pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
        'FaceDetectorMLKit'
    ]
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "React"
            target.remove_from_project
        end
    end
end
